### ISSUE TITLE
TypeError: Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by akakoori** [akakoori/drrrbot#1]
(Sat Jul 02 2016 00:01:40 GMT+0800 (CST):24.72MB)
Caught exception：TypeError: Cannot read property 'device' of undefined 
at app/lib/bot.js:832:49 
at app/node_modules/async/lib/async.js:181:20 
at Object.async.forEachOf.async.eachOf (app/node_modules/async/lib/async.js:233:13) 
at Object.async.forEach.async.each (app/node_modules/async/lib/async.js:209:22) 

line 832:

> if (!talk.is_me && talk.from.device !== 'bot') 

难道还有type为message却没有talk.from的情况？

**Comment by akakoori** [comment]
从debug来看，似乎是因为莫名的原因掉出了房间，但是talk.from为何会没有？

**Comment by akakoori** [comment]
![image](https://cloud.githubusercontent.com/assets/15867066/16538117/eab40330-404b-11e6-98dd-2a00884a1132.png)

看起来是聊天室服务器的问题，确实有时候会遗失talk.from.
